"""
Edit engine — the core "edit-based generation" module.

Models PPT generation as a sequence of atomic edit operations (add, delete,
modify) on a presentation. Each operation is either:
- Generated by an LLM (via function calling)
- Derived from HTML diffing
- Specified programmatically
"""

from src.editing.operations import EditOperation, EditOpType
from src.editing.editor import EditEngine
from src.editing.llm_editor import LLMEditor

__all__ = [
    "EditOperation",
    "EditOpType",
    "EditEngine",
    "LLMEditor",
]
